# Generated by Django 4.1 on 2022-08-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_date'], 'verbose_name_plural': 'News'},
        ),
        migrations.AlterField(
            model_name='likes',
            name='likes_to',
            field=models.PositiveIntegerField(),
        ),
    ]
