# Generated by Django 4.1 on 2022-08-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='likes_to',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='likes',
            constraint=models.UniqueConstraint(fields=('likes_to', 'likes_from'), name='unique_like'),
        ),
    ]
