# Generated by Django 4.1 on 2022-08-11 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_likes_options_alter_news_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-comment_date'], 'verbose_name_plural': 'Comments'},
        ),
    ]
